// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq95S7S7YZOxnyxHYLKWBYofsbtJPzVqg',
    appId: '1:273565916500:web:9df43d75d355e73e89bcc1',
    messagingSenderId: '273565916500',
    projectId: 'peercode-1800b',
    authDomain: 'peercode-1800b.firebaseapp.com',
    storageBucket: 'peercode-1800b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92ex5Z5l-zqqmGCgCwV5iWTi0NyPnHp4',
    appId: '1:273565916500:android:02b266dea391efdf89bcc1',
    messagingSenderId: '273565916500',
    projectId: 'peercode-1800b',
    storageBucket: 'peercode-1800b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi84gbaphEX3sXgM8ypkUyF3ybrwbx6ng',
    appId: '1:273565916500:ios:a5a6a7b257b8ecd489bcc1',
    messagingSenderId: '273565916500',
    projectId: 'peercode-1800b',
    storageBucket: 'peercode-1800b.firebasestorage.app',
    iosBundleId: 'com.example.atrisPeercode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi84gbaphEX3sXgM8ypkUyF3ybrwbx6ng',
    appId: '1:273565916500:ios:a5a6a7b257b8ecd489bcc1',
    messagingSenderId: '273565916500',
    projectId: 'peercode-1800b',
    storageBucket: 'peercode-1800b.firebasestorage.app',
    iosBundleId: 'com.example.atrisPeercode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq95S7S7YZOxnyxHYLKWBYofsbtJPzVqg',
    appId: '1:273565916500:web:3ec88689036208d789bcc1',
    messagingSenderId: '273565916500',
    projectId: 'peercode-1800b',
    authDomain: 'peercode-1800b.firebaseapp.com',
    storageBucket: 'peercode-1800b.firebasestorage.app',
  );
}
